import { EarthMindTheme, ThemePresetId } from './ThemeTokens';

export const THEME_PRESETS: Record<ThemePresetId, EarthMindTheme> = {
  // 1. EARTHMIND PURE - Bright, minimal, clean, scientific
  pure: {
    id: 'pure',
    name: 'EarthMind Pure',
    description: 'Crisp scientific clarity, clean neutral glass and pristine contrast',
    colors: {
      bg: '#0A141E',
      surface: 'rgba(16, 28, 40, 0.72)',
      surfaceElevated: 'rgba(24, 42, 60, 0.85)',
      glass: 'rgba(255, 255, 255, 0.05)',
      glassStrong: 'rgba(255, 255, 255, 0.12)',
      glassSoft: 'rgba(255, 255, 255, 0.03)',
      border: 'rgba(255, 255, 255, 0.14)',
      borderBright: 'rgba(255, 255, 255, 0.35)',
      text: '#F8FAFC',
      textSecondary: '#94A3B8',
      textMuted: '#64748B',
      accent: '#38BDF8',
      accentSoft: 'rgba(56, 189, 248, 0.15)',
      accentSecondary: '#818CF8',
      success: '#34D399',
      warning: '#FBBF24',
      danger: '#F87171',
      info: '#38BDF8',
      shadow: 'rgba(0, 0, 0, 0.45)',
      glow: 'rgba(56, 189, 248, 0.25)',
    },
    glass: {
      opacity: 68,
      blur: 60,
      saturation: 110,
      brightness: 105,
      density: 50,
      reflection: 45,
      noise: 10,
      borderVisibility: 55,
      borderBrightness: 60,
    },
    depth: {
      shadow: 50,
      elevation: 60,
      ambientLight: 55,
      surfaceDepth: 65,
      glow: 40,
    },
    shape: {
      cornerRadius: 45,
      panelRoundness: 50,
      buttonRoundness: 40,
      chipRoundness: 90,
    },
    typography: {
      fontFamily: 'Plus Jakarta Sans',
      fontSizeScale: 100,
      fontWeightBase: 400,
      letterSpacing: 0,
      lineHeightScale: 100,
      headingScale: 100,
      dataScale: 100,
    },
    motion: {
      intensity: 65,
      hoverMotion: 70,
      entranceMotion: 60,
      transitionSpeed: 60,
      parallax: 40,
      glassRefraction: 50,
      particleMotion: 40,
    },
    layout: {
      density: 50,
      panelSpacing: 50,
      contentWidth: 80,
      navigationWidth: 60,
      sidebarDensity: 50,
      informationDensity: 60,
    },
    earth: {
      glow: 60,
      atmosphere: 65,
      cloudVisibility: 70,
      nightLights: 75,
      brightness: 65,
      contrast: 60,
      saturation: 60,
      scale: 50,
      rotationSpeed: 50,
    },
    map: {
      opacity: 75,
      contrast: 60,
      labels: 65,
      grid: 40,
      boundaryStrength: 50,
      heatmapIntensity: 65,
    },
    data: {
      chartGlow: 50,
      chartThickness: 50,
      gridVisibility: 40,
      labelDensity: 60,
      dataAnimation: 60,
    },
    accessibility: {
      reduceMotion: false,
      highContrast: false,
      largeText: false,
      focusVisibility: true,
      colorBlindMode: 'none',
      screenReaderOptimized: false,
    },
    performance: 'high',
  },

  // 2. EARTHMIND GLASS - High transparency, soft blur, floating panels
  glass: {
    id: 'glass',
    name: 'EarthMind Glass',
    description: 'Maximized optical translucency, ethereal deep blur and refraction',
    colors: {
      bg: '#050D18',
      surface: 'rgba(8, 22, 38, 0.45)',
      surfaceElevated: 'rgba(12, 32, 54, 0.62)',
      glass: 'rgba(255, 255, 255, 0.08)',
      glassStrong: 'rgba(255, 255, 255, 0.18)',
      glassSoft: 'rgba(255, 255, 255, 0.04)',
      border: 'rgba(255, 255, 255, 0.18)',
      borderBright: 'rgba(255, 255, 255, 0.5)',
      text: '#FFFFFF',
      textSecondary: '#CBD5E1',
      textMuted: '#64748B',
      accent: '#22D3EE',
      accentSoft: 'rgba(34, 211, 238, 0.18)',
      accentSecondary: '#A78BFA',
      success: '#4ADE80',
      warning: '#FBBF24',
      danger: '#FB7185',
      info: '#38BDF8',
      shadow: 'rgba(0, 0, 0, 0.55)',
      glow: 'rgba(34, 211, 238, 0.35)',
    },
    glass: {
      opacity: 85,
      blur: 85,
      saturation: 135,
      brightness: 110,
      density: 70,
      reflection: 75,
      noise: 15,
      borderVisibility: 70,
      borderBrightness: 80,
    },
    depth: {
      shadow: 75,
      elevation: 80,
      ambientLight: 70,
      surfaceDepth: 85,
      glow: 65,
    },
    shape: {
      cornerRadius: 65,
      panelRoundness: 70,
      buttonRoundness: 55,
      chipRoundness: 95,
    },
    typography: {
      fontFamily: 'Plus Jakarta Sans',
      fontSizeScale: 100,
      fontWeightBase: 400,
      letterSpacing: 0,
      lineHeightScale: 100,
      headingScale: 100,
      dataScale: 100,
    },
    motion: {
      intensity: 75,
      hoverMotion: 85,
      entranceMotion: 75,
      transitionSpeed: 70,
      parallax: 60,
      glassRefraction: 80,
      particleMotion: 60,
    },
    layout: {
      density: 55,
      panelSpacing: 60,
      contentWidth: 85,
      navigationWidth: 65,
      sidebarDensity: 50,
      informationDensity: 65,
    },
    earth: {
      glow: 75,
      atmosphere: 80,
      cloudVisibility: 75,
      nightLights: 80,
      brightness: 70,
      contrast: 65,
      saturation: 70,
      scale: 55,
      rotationSpeed: 55,
    },
    map: {
      opacity: 80,
      contrast: 65,
      labels: 70,
      grid: 45,
      boundaryStrength: 60,
      heatmapIntensity: 70,
    },
    data: {
      chartGlow: 70,
      chartThickness: 55,
      gridVisibility: 45,
      labelDensity: 65,
      dataAnimation: 75,
    },
    accessibility: {
      reduceMotion: false,
      highContrast: false,
      largeText: false,
      focusVisibility: true,
      colorBlindMode: 'none',
      screenReaderOptimized: false,
    },
    performance: 'ultra',
  },

  // 3. EARTHMIND AURORA - Default signature with atmospheric cyan/purple/emerald gradients
  aurora: {
    id: 'aurora',
    name: 'EarthMind Aurora',
    description: 'Planetary signature with atmospheric ionosphere glow and layered radiance',
    colors: {
      bg: '#071A2B',
      surface: 'rgba(9, 28, 48, 0.72)',
      surfaceElevated: 'rgba(16, 42, 69, 0.82)',
      glass: 'rgba(24, 200, 200, 0.08)',
      glassStrong: 'rgba(24, 200, 200, 0.16)',
      glassSoft: 'rgba(255, 255, 255, 0.04)',
      border: 'rgba(255, 255, 255, 0.12)',
      borderBright: 'rgba(24, 200, 200, 0.35)',
      text: '#F1F5F9',
      textSecondary: '#94A3B8',
      textMuted: '#64748B',
      accent: '#18C8C8',
      accentSoft: 'rgba(24, 200, 200, 0.15)',
      accentSecondary: '#9B7CFF',
      success: '#27C98A',
      warning: '#FFD166',
      danger: '#FF6B6B',
      info: '#4FA8FF',
      shadow: 'rgba(7, 26, 43, 0.7)',
      glow: 'rgba(24, 200, 200, 0.28)',
    },
    glass: {
      opacity: 75,
      blur: 70,
      saturation: 125,
      brightness: 105,
      density: 60,
      reflection: 65,
      noise: 12,
      borderVisibility: 65,
      borderBrightness: 70,
    },
    depth: {
      shadow: 65,
      elevation: 70,
      ambientLight: 65,
      surfaceDepth: 75,
      glow: 60,
    },
    shape: {
      cornerRadius: 55,
      panelRoundness: 60,
      buttonRoundness: 45,
      chipRoundness: 90,
    },
    typography: {
      fontFamily: 'Plus Jakarta Sans',
      fontSizeScale: 100,
      fontWeightBase: 400,
      letterSpacing: 0,
      lineHeightScale: 100,
      headingScale: 100,
      dataScale: 100,
    },
    motion: {
      intensity: 70,
      hoverMotion: 75,
      entranceMotion: 65,
      transitionSpeed: 65,
      parallax: 50,
      glassRefraction: 65,
      particleMotion: 50,
    },
    layout: {
      density: 50,
      panelSpacing: 50,
      contentWidth: 80,
      navigationWidth: 60,
      sidebarDensity: 50,
      informationDensity: 60,
    },
    earth: {
      glow: 70,
      atmosphere: 75,
      cloudVisibility: 70,
      nightLights: 75,
      brightness: 65,
      contrast: 65,
      saturation: 70,
      scale: 50,
      rotationSpeed: 50,
    },
    map: {
      opacity: 75,
      contrast: 65,
      labels: 65,
      grid: 40,
      boundaryStrength: 55,
      heatmapIntensity: 70,
    },
    data: {
      chartGlow: 65,
      chartThickness: 50,
      gridVisibility: 40,
      labelDensity: 60,
      dataAnimation: 65,
    },
    accessibility: {
      reduceMotion: false,
      highContrast: false,
      largeText: false,
      focusVisibility: true,
      colorBlindMode: 'none',
      screenReaderOptimized: false,
    },
    performance: 'high',
  },

  // 4. EARTHMIND OCEAN - Blue/cyan scientific appearance
  ocean: {
    id: 'ocean',
    name: 'EarthMind Ocean',
    description: 'Deep pelagic blues, sea ice luminescence, and hydro-spectral clarity',
    colors: {
      bg: '#04101E',
      surface: 'rgba(6, 26, 48, 0.75)',
      surfaceElevated: 'rgba(8, 38, 70, 0.88)',
      glass: 'rgba(14, 165, 233, 0.08)',
      glassStrong: 'rgba(14, 165, 233, 0.18)',
      glassSoft: 'rgba(255, 255, 255, 0.03)',
      border: 'rgba(56, 189, 248, 0.2)',
      borderBright: 'rgba(56, 189, 248, 0.45)',
      text: '#F0F9FF',
      textSecondary: '#7DD3FC',
      textMuted: '#0369A1',
      accent: '#0284C7',
      accentSoft: 'rgba(2, 132, 199, 0.18)',
      accentSecondary: '#06B6D4',
      success: '#10B981',
      warning: '#F59E0B',
      danger: '#EF4444',
      info: '#38BDF8',
      shadow: 'rgba(2, 18, 36, 0.75)',
      glow: 'rgba(14, 165, 233, 0.35)',
    },
    glass: {
      opacity: 78,
      blur: 75,
      saturation: 130,
      brightness: 105,
      density: 65,
      reflection: 60,
      noise: 10,
      borderVisibility: 65,
      borderBrightness: 70,
    },
    depth: {
      shadow: 70,
      elevation: 75,
      ambientLight: 60,
      surfaceDepth: 80,
      glow: 65,
    },
    shape: {
      cornerRadius: 50,
      panelRoundness: 55,
      buttonRoundness: 40,
      chipRoundness: 90,
    },
    typography: {
      fontFamily: 'Plus Jakarta Sans',
      fontSizeScale: 100,
      fontWeightBase: 400,
      letterSpacing: 0,
      lineHeightScale: 100,
      headingScale: 100,
      dataScale: 100,
    },
    motion: {
      intensity: 65,
      hoverMotion: 70,
      entranceMotion: 60,
      transitionSpeed: 60,
      parallax: 45,
      glassRefraction: 60,
      particleMotion: 45,
    },
    layout: {
      density: 50,
      panelSpacing: 50,
      contentWidth: 80,
      navigationWidth: 60,
      sidebarDensity: 50,
      informationDensity: 60,
    },
    earth: {
      glow: 75,
      atmosphere: 80,
      cloudVisibility: 70,
      nightLights: 70,
      brightness: 65,
      contrast: 70,
      saturation: 80,
      scale: 50,
      rotationSpeed: 45,
    },
    map: {
      opacity: 80,
      contrast: 70,
      labels: 65,
      grid: 45,
      boundaryStrength: 60,
      heatmapIntensity: 75,
    },
    data: {
      chartGlow: 70,
      chartThickness: 50,
      gridVisibility: 45,
      labelDensity: 60,
      dataAnimation: 60,
    },
    accessibility: {
      reduceMotion: false,
      highContrast: false,
      largeText: false,
      focusVisibility: true,
      colorBlindMode: 'none',
      screenReaderOptimized: false,
    },
    performance: 'high',
  },

  // 5. EARTHMIND FOREST - Green environmental intelligence
  forest: {
    id: 'forest',
    name: 'EarthMind Forest',
    description: 'Emerald biosphere radiance, photosynthetic NDVI accents and canopy depth',
    colors: {
      bg: '#051811',
      surface: 'rgba(8, 36, 24, 0.75)',
      surfaceElevated: 'rgba(12, 52, 34, 0.88)',
      glass: 'rgba(39, 201, 138, 0.08)',
      glassStrong: 'rgba(39, 201, 138, 0.18)',
      glassSoft: 'rgba(255, 255, 255, 0.03)',
      border: 'rgba(39, 201, 138, 0.22)',
      borderBright: 'rgba(39, 201, 138, 0.48)',
      text: '#F0FDF4',
      textSecondary: '#86EFAC',
      textMuted: '#166534',
      accent: '#27C98A',
      accentSoft: 'rgba(39, 201, 138, 0.18)',
      accentSecondary: '#75D66A',
      success: '#22C55E',
      warning: '#EAB308',
      danger: '#F43F5E',
      info: '#14B8A6',
      shadow: 'rgba(2, 24, 15, 0.75)',
      glow: 'rgba(39, 201, 138, 0.32)',
    },
    glass: {
      opacity: 76,
      blur: 70,
      saturation: 125,
      brightness: 105,
      density: 60,
      reflection: 60,
      noise: 12,
      borderVisibility: 65,
      borderBrightness: 70,
    },
    depth: {
      shadow: 65,
      elevation: 70,
      ambientLight: 65,
      surfaceDepth: 75,
      glow: 60,
    },
    shape: {
      cornerRadius: 50,
      panelRoundness: 55,
      buttonRoundness: 40,
      chipRoundness: 90,
    },
    typography: {
      fontFamily: 'Plus Jakarta Sans',
      fontSizeScale: 100,
      fontWeightBase: 400,
      letterSpacing: 0,
      lineHeightScale: 100,
      headingScale: 100,
      dataScale: 100,
    },
    motion: {
      intensity: 65,
      hoverMotion: 70,
      entranceMotion: 60,
      transitionSpeed: 60,
      parallax: 40,
      glassRefraction: 60,
      particleMotion: 40,
    },
    layout: {
      density: 50,
      panelSpacing: 50,
      contentWidth: 80,
      navigationWidth: 60,
      sidebarDensity: 50,
      informationDensity: 60,
    },
    earth: {
      glow: 70,
      atmosphere: 75,
      cloudVisibility: 70,
      nightLights: 65,
      brightness: 65,
      contrast: 65,
      saturation: 75,
      scale: 50,
      rotationSpeed: 50,
    },
    map: {
      opacity: 80,
      contrast: 65,
      labels: 65,
      grid: 40,
      boundaryStrength: 55,
      heatmapIntensity: 75,
    },
    data: {
      chartGlow: 65,
      chartThickness: 50,
      gridVisibility: 40,
      labelDensity: 60,
      dataAnimation: 60,
    },
    accessibility: {
      reduceMotion: false,
      highContrast: false,
      largeText: false,
      focusVisibility: true,
      colorBlindMode: 'none',
      screenReaderOptimized: false,
    },
    performance: 'high',
  },

  // 6. EARTHMIND ARCTIC - White/ice/glass
  arctic: {
    id: 'arctic',
    name: 'EarthMind Arctic',
    description: 'Glacial cryosphere aesthetic, crystalline ice glass and diamond luminescence',
    colors: {
      bg: '#08121E',
      surface: 'rgba(18, 36, 56, 0.65)',
      surfaceElevated: 'rgba(26, 50, 76, 0.82)',
      glass: 'rgba(224, 242, 254, 0.12)',
      glassStrong: 'rgba(224, 242, 254, 0.22)',
      glassSoft: 'rgba(255, 255, 255, 0.06)',
      border: 'rgba(186, 230, 253, 0.28)',
      borderBright: 'rgba(255, 255, 255, 0.65)',
      text: '#F8FAFC',
      textSecondary: '#BAE6FD',
      textMuted: '#64748B',
      accent: '#7DD3FC',
      accentSoft: 'rgba(125, 211, 252, 0.18)',
      accentSecondary: '#E0F2FE',
      success: '#34D399',
      warning: '#FBBF24',
      danger: '#F87171',
      info: '#38BDF8',
      shadow: 'rgba(3, 10, 18, 0.65)',
      glow: 'rgba(186, 230, 253, 0.35)',
    },
    glass: {
      opacity: 82,
      blur: 80,
      saturation: 120,
      brightness: 115,
      density: 68,
      reflection: 80,
      noise: 18,
      borderVisibility: 75,
      borderBrightness: 85,
    },
    depth: {
      shadow: 70,
      elevation: 75,
      ambientLight: 75,
      surfaceDepth: 80,
      glow: 70,
    },
    shape: {
      cornerRadius: 60,
      panelRoundness: 65,
      buttonRoundness: 50,
      chipRoundness: 95,
    },
    typography: {
      fontFamily: 'Plus Jakarta Sans',
      fontSizeScale: 100,
      fontWeightBase: 400,
      letterSpacing: 0,
      lineHeightScale: 100,
      headingScale: 100,
      dataScale: 100,
    },
    motion: {
      intensity: 70,
      hoverMotion: 80,
      entranceMotion: 70,
      transitionSpeed: 65,
      parallax: 55,
      glassRefraction: 75,
      particleMotion: 55,
    },
    layout: {
      density: 50,
      panelSpacing: 50,
      contentWidth: 80,
      navigationWidth: 60,
      sidebarDensity: 50,
      informationDensity: 60,
    },
    earth: {
      glow: 80,
      atmosphere: 85,
      cloudVisibility: 80,
      nightLights: 70,
      brightness: 75,
      contrast: 70,
      saturation: 65,
      scale: 50,
      rotationSpeed: 45,
    },
    map: {
      opacity: 80,
      contrast: 70,
      labels: 70,
      grid: 45,
      boundaryStrength: 60,
      heatmapIntensity: 70,
    },
    data: {
      chartGlow: 70,
      chartThickness: 50,
      gridVisibility: 45,
      labelDensity: 60,
      dataAnimation: 65,
    },
    accessibility: {
      reduceMotion: false,
      highContrast: false,
      largeText: false,
      focusVisibility: true,
      colorBlindMode: 'none',
      screenReaderOptimized: false,
    },
    performance: 'high',
  },

  // 7. EARTHMIND MISSION - Aerospace command center (amber/cyan stealth)
  mission: {
    id: 'mission',
    name: 'EarthMind Mission',
    description: 'Aerospace command telemetry, tactical amber HUD and ultra-low noise dark stealth',
    colors: {
      bg: '#04070B',
      surface: 'rgba(8, 14, 22, 0.85)',
      surfaceElevated: 'rgba(14, 22, 34, 0.95)',
      glass: 'rgba(245, 158, 11, 0.06)',
      glassStrong: 'rgba(245, 158, 11, 0.14)',
      glassSoft: 'rgba(255, 255, 255, 0.02)',
      border: 'rgba(245, 158, 11, 0.22)',
      borderBright: 'rgba(245, 158, 11, 0.55)',
      text: '#F8FAFC',
      textSecondary: '#FCD34D',
      textMuted: '#78350F',
      accent: '#F59E0B',
      accentSoft: 'rgba(245, 158, 11, 0.16)',
      accentSecondary: '#06B6D4',
      success: '#10B981',
      warning: '#F59E0B',
      danger: '#EF4444',
      info: '#06B6D4',
      shadow: 'rgba(0, 0, 0, 0.85)',
      glow: 'rgba(245, 158, 11, 0.35)',
    },
    glass: {
      opacity: 70,
      blur: 55,
      saturation: 110,
      brightness: 100,
      density: 50,
      reflection: 50,
      noise: 8,
      borderVisibility: 70,
      borderBrightness: 75,
    },
    depth: {
      shadow: 75,
      elevation: 70,
      ambientLight: 45,
      surfaceDepth: 75,
      glow: 60,
    },
    shape: {
      cornerRadius: 30,
      panelRoundness: 35,
      buttonRoundness: 25,
      chipRoundness: 50,
    },
    typography: {
      fontFamily: 'JetBrains Mono',
      fontSizeScale: 95,
      fontWeightBase: 500,
      letterSpacing: 1,
      lineHeightScale: 95,
      headingScale: 95,
      dataScale: 105,
    },
    motion: {
      intensity: 50,
      hoverMotion: 55,
      entranceMotion: 45,
      transitionSpeed: 50,
      parallax: 30,
      glassRefraction: 40,
      particleMotion: 30,
    },
    layout: {
      density: 75,
      panelSpacing: 40,
      contentWidth: 90,
      navigationWidth: 55,
      sidebarDensity: 75,
      informationDensity: 85,
    },
    earth: {
      glow: 65,
      atmosphere: 65,
      cloudVisibility: 65,
      nightLights: 85,
      brightness: 60,
      contrast: 75,
      saturation: 60,
      scale: 50,
      rotationSpeed: 40,
    },
    map: {
      opacity: 85,
      contrast: 80,
      labels: 75,
      grid: 65,
      boundaryStrength: 75,
      heatmapIntensity: 80,
    },
    data: {
      chartGlow: 65,
      chartThickness: 60,
      gridVisibility: 60,
      labelDensity: 80,
      dataAnimation: 50,
    },
    accessibility: {
      reduceMotion: false,
      highContrast: true,
      largeText: false,
      focusVisibility: true,
      colorBlindMode: 'none',
      screenReaderOptimized: false,
    },
    performance: 'ultra',
  },

  // 8. EARTHMIND MONO - Single-color luxury monochrome
  mono: {
    id: 'mono',
    name: 'EarthMind Mono',
    description: 'Minimalist high-fashion monochromatic glass with precision typography',
    colors: {
      bg: '#09090B',
      surface: 'rgba(24, 24, 27, 0.75)',
      surfaceElevated: 'rgba(39, 39, 42, 0.88)',
      glass: 'rgba(255, 255, 255, 0.05)',
      glassStrong: 'rgba(255, 255, 255, 0.12)',
      glassSoft: 'rgba(255, 255, 255, 0.02)',
      border: 'rgba(255, 255, 255, 0.15)',
      borderBright: 'rgba(255, 255, 255, 0.4)',
      text: '#FAFAFA',
      textSecondary: '#A1A1AA',
      textMuted: '#52525B',
      accent: '#FAFAFA',
      accentSoft: 'rgba(255, 255, 255, 0.12)',
      accentSecondary: '#A1A1AA',
      success: '#E4E4E7',
      warning: '#D4D4D8',
      danger: '#A1A1AA',
      info: '#FAFAFA',
      shadow: 'rgba(0, 0, 0, 0.65)',
      glow: 'rgba(255, 255, 255, 0.18)',
    },
    glass: {
      opacity: 70,
      blur: 65,
      saturation: 100,
      brightness: 105,
      density: 50,
      reflection: 50,
      noise: 10,
      borderVisibility: 60,
      borderBrightness: 65,
    },
    depth: {
      shadow: 60,
      elevation: 65,
      ambientLight: 50,
      surfaceDepth: 70,
      glow: 35,
    },
    shape: {
      cornerRadius: 45,
      panelRoundness: 50,
      buttonRoundness: 35,
      chipRoundness: 90,
    },
    typography: {
      fontFamily: 'Inter',
      fontSizeScale: 100,
      fontWeightBase: 400,
      letterSpacing: 0,
      lineHeightScale: 100,
      headingScale: 100,
      dataScale: 100,
    },
    motion: {
      intensity: 60,
      hoverMotion: 65,
      entranceMotion: 55,
      transitionSpeed: 55,
      parallax: 35,
      glassRefraction: 45,
      particleMotion: 35,
    },
    layout: {
      density: 50,
      panelSpacing: 50,
      contentWidth: 80,
      navigationWidth: 60,
      sidebarDensity: 50,
      informationDensity: 60,
    },
    earth: {
      glow: 50,
      atmosphere: 55,
      cloudVisibility: 65,
      nightLights: 70,
      brightness: 60,
      contrast: 65,
      saturation: 40,
      scale: 50,
      rotationSpeed: 45,
    },
    map: {
      opacity: 75,
      contrast: 65,
      labels: 65,
      grid: 40,
      boundaryStrength: 50,
      heatmapIntensity: 60,
    },
    data: {
      chartGlow: 40,
      chartThickness: 50,
      gridVisibility: 40,
      labelDensity: 60,
      dataAnimation: 55,
    },
    accessibility: {
      reduceMotion: false,
      highContrast: false,
      largeText: false,
      focusVisibility: true,
      colorBlindMode: 'none',
      screenReaderOptimized: false,
    },
    performance: 'high',
  },

  // 9. EARTHMIND EXPO - Presentation optimized, huge readability
  expo: {
    id: 'expo',
    name: 'EarthMind Expo',
    description: 'High-visibility Science Expo mode with bold fonts, elevated contrast and projection tuning',
    colors: {
      bg: '#041528',
      surface: 'rgba(8, 30, 54, 0.88)',
      surfaceElevated: 'rgba(14, 46, 80, 0.95)',
      glass: 'rgba(255, 209, 102, 0.08)',
      glassStrong: 'rgba(24, 200, 200, 0.22)',
      glassSoft: 'rgba(255, 255, 255, 0.05)',
      border: 'rgba(255, 255, 255, 0.22)',
      borderBright: 'rgba(255, 209, 102, 0.55)',
      text: '#FFFFFF',
      textSecondary: '#E2E8F0',
      textMuted: '#94A3B8',
      accent: '#FFD166',
      accentSoft: 'rgba(255, 209, 102, 0.2)',
      accentSecondary: '#18C8C8',
      success: '#27C98A',
      warning: '#FFD166',
      danger: '#FF6B6B',
      info: '#4FA8FF',
      shadow: 'rgba(0, 0, 0, 0.75)',
      glow: 'rgba(255, 209, 102, 0.4)',
    },
    glass: {
      opacity: 78,
      blur: 70,
      saturation: 130,
      brightness: 110,
      density: 65,
      reflection: 70,
      noise: 10,
      borderVisibility: 75,
      borderBrightness: 80,
    },
    depth: {
      shadow: 75,
      elevation: 80,
      ambientLight: 75,
      surfaceDepth: 80,
      glow: 75,
    },
    shape: {
      cornerRadius: 60,
      panelRoundness: 65,
      buttonRoundness: 50,
      chipRoundness: 95,
    },
    typography: {
      fontFamily: 'Plus Jakarta Sans',
      fontSizeScale: 115,
      fontWeightBase: 500,
      letterSpacing: 0.5,
      lineHeightScale: 110,
      headingScale: 120,
      dataScale: 125,
    },
    motion: {
      intensity: 75,
      hoverMotion: 80,
      entranceMotion: 70,
      transitionSpeed: 70,
      parallax: 50,
      glassRefraction: 70,
      particleMotion: 50,
    },
    layout: {
      density: 40,
      panelSpacing: 65,
      contentWidth: 85,
      navigationWidth: 70,
      sidebarDensity: 40,
      informationDensity: 60,
    },
    earth: {
      glow: 85,
      atmosphere: 85,
      cloudVisibility: 75,
      nightLights: 85,
      brightness: 75,
      contrast: 70,
      saturation: 75,
      scale: 60,
      rotationSpeed: 55,
    },
    map: {
      opacity: 85,
      contrast: 75,
      labels: 80,
      grid: 50,
      boundaryStrength: 70,
      heatmapIntensity: 80,
    },
    data: {
      chartGlow: 80,
      chartThickness: 65,
      gridVisibility: 50,
      labelDensity: 75,
      dataAnimation: 75,
    },
    accessibility: {
      reduceMotion: false,
      highContrast: true,
      largeText: true,
      focusVisibility: true,
      colorBlindMode: 'none',
      screenReaderOptimized: false,
    },
    performance: 'ultra',
  },

  // 10. CUSTOM - User-defined template initialized from Aurora
  custom: {
    id: 'custom',
    name: 'Custom Theme',
    description: 'Personalized planetary intelligence workstation customized to operator preferences',
    colors: {
      bg: '#071A2B',
      surface: 'rgba(9, 28, 48, 0.72)',
      surfaceElevated: 'rgba(16, 42, 69, 0.82)',
      glass: 'rgba(24, 200, 200, 0.08)',
      glassStrong: 'rgba(24, 200, 200, 0.16)',
      glassSoft: 'rgba(255, 255, 255, 0.04)',
      border: 'rgba(255, 255, 255, 0.12)',
      borderBright: 'rgba(24, 200, 200, 0.35)',
      text: '#F1F5F9',
      textSecondary: '#94A3B8',
      textMuted: '#64748B',
      accent: '#18C8C8',
      accentSoft: 'rgba(24, 200, 200, 0.15)',
      accentSecondary: '#9B7CFF',
      success: '#27C98A',
      warning: '#FFD166',
      danger: '#FF6B6B',
      info: '#4FA8FF',
      shadow: 'rgba(7, 26, 43, 0.7)',
      glow: 'rgba(24, 200, 200, 0.28)',
    },
    glass: {
      opacity: 75,
      blur: 70,
      saturation: 125,
      brightness: 105,
      density: 60,
      reflection: 65,
      noise: 12,
      borderVisibility: 65,
      borderBrightness: 70,
    },
    depth: {
      shadow: 65,
      elevation: 70,
      ambientLight: 65,
      surfaceDepth: 75,
      glow: 60,
    },
    shape: {
      cornerRadius: 55,
      panelRoundness: 60,
      buttonRoundness: 45,
      chipRoundness: 90,
    },
    typography: {
      fontFamily: 'Plus Jakarta Sans',
      fontSizeScale: 100,
      fontWeightBase: 400,
      letterSpacing: 0,
      lineHeightScale: 100,
      headingScale: 100,
      dataScale: 100,
    },
    motion: {
      intensity: 70,
      hoverMotion: 75,
      entranceMotion: 65,
      transitionSpeed: 65,
      parallax: 50,
      glassRefraction: 65,
      particleMotion: 50,
    },
    layout: {
      density: 50,
      panelSpacing: 50,
      contentWidth: 80,
      navigationWidth: 60,
      sidebarDensity: 50,
      informationDensity: 60,
    },
    earth: {
      glow: 70,
      atmosphere: 75,
      cloudVisibility: 70,
      nightLights: 75,
      brightness: 65,
      contrast: 65,
      saturation: 70,
      scale: 50,
      rotationSpeed: 50,
    },
    map: {
      opacity: 75,
      contrast: 65,
      labels: 65,
      grid: 40,
      boundaryStrength: 55,
      heatmapIntensity: 70,
    },
    data: {
      chartGlow: 65,
      chartThickness: 50,
      gridVisibility: 40,
      labelDensity: 60,
      dataAnimation: 65,
    },
    accessibility: {
      reduceMotion: false,
      highContrast: false,
      largeText: false,
      focusVisibility: true,
      colorBlindMode: 'none',
      screenReaderOptimized: false,
    },
    performance: 'high',
  },
};
