declare module 'lucide-react' {
  import * as React from 'react';
  export interface LucideProps extends React.SVGProps<SVGSVGElement> {
    size?: string | number;
    color?: string;
    strokeWidth?: string | number;
    className?: string;
  }
  export type LucideIcon = React.FC<LucideProps>;
  
  export const Activity: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const ArrowDownRight: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const ArrowUpRight: LucideIcon;
  export const Award: LucideIcon;
  export const BarChart3: LucideIcon;
  export const Binary: LucideIcon;
  export const Bot: LucideIcon;
  export const Building2: LucideIcon;
  export const Calendar: LucideIcon;
  export const Car: LucideIcon;
  export const Check: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const Clock: LucideIcon;
  export const CloudRain: LucideIcon;
  export const Compass: LucideIcon;
  export const Cpu: LucideIcon;
  export const Database: LucideIcon;
  export const DollarSign: LucideIcon;
  export const Download: LucideIcon;
  export const Droplets: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const Eye: LucideIcon;
  export const Factory: LucideIcon;
  export const FileText: LucideIcon;
  export const Flame: LucideIcon;
  export const FlaskConical: LucideIcon;
  export const Gauge: LucideIcon;
  export const Globe: LucideIcon;
  export const Globe2: LucideIcon;
  export const Grid: LucideIcon;
  export const HardDrive: LucideIcon;
  export const HeartHandshake: LucideIcon;
  export const HelpCircle: LucideIcon;
  export const History: LucideIcon;
  export const Info: LucideIcon;
  export const Layers: LucideIcon;
  export const Leaf: LucideIcon;
  export const Lightbulb: LucideIcon;
  export const MapPin: LucideIcon;
  export const Maximize2: LucideIcon;
  export const Minimize2: LucideIcon;
  export const Minus: LucideIcon;
  export const Pause: LucideIcon;
  export const Play: LucideIcon;
  export const Plus: LucideIcon;
  export const Presentation: LucideIcon;
  export const Printer: LucideIcon;
  export const RotateCcw: LucideIcon;
  export const Satellite: LucideIcon;
  export const Save: LucideIcon;
  export const Scale: LucideIcon;
  export const Search: LucideIcon;
  export const Send: LucideIcon;
  export const Settings: LucideIcon;
  export const Share2: LucideIcon;
  export const ShieldAlert: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const SkipForward: LucideIcon;
  export const Sliders: LucideIcon;
  export const Sparkles: LucideIcon;
  export const Sun: LucideIcon;
  export const Target: LucideIcon;
  export const Trash2: LucideIcon;
  export const Trees: LucideIcon;
  export const TrendingDown: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Volume2: LucideIcon;
  export const VolumeX: LucideIcon;
  export const Mic: LucideIcon;
  export const MicOff: LucideIcon;
  export const Terminal: LucideIcon;
  export const XCircle: LucideIcon;
  export const Waves: LucideIcon;
  export const Wind: LucideIcon;
  export const X: LucideIcon;
  export const Zap: LucideIcon;
}

